/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.dbb.common.language.provider.db.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Translation service. Represents a row in the &quot;INTERNATIONAL_Translation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.dbb.common.language.provider.db.model.impl.TranslationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.dbb.common.language.provider.db.model.impl.TranslationImpl</code>.
 * </p>
 *
 * @author danielebb
 * @see Translation
 * @generated
 */
@ProviderType
public interface TranslationModel
	extends BaseModel<Translation>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a translation model instance should use the {@link Translation} interface instead.
	 */

	/**
	 * Returns the primary key of this translation.
	 *
	 * @return the primary key of this translation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this translation.
	 *
	 * @param primaryKey the primary key of this translation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this translation.
	 *
	 * @return the uuid of this translation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this translation.
	 *
	 * @param uuid the uuid of this translation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the translation ID of this translation.
	 *
	 * @return the translation ID of this translation
	 */
	public long getTranslationId();

	/**
	 * Sets the translation ID of this translation.
	 *
	 * @param translationId the translation ID of this translation
	 */
	public void setTranslationId(long translationId);

	/**
	 * Returns the company ID of this translation.
	 *
	 * @return the company ID of this translation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this translation.
	 *
	 * @param companyId the company ID of this translation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this translation.
	 *
	 * @return the user ID of this translation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this translation.
	 *
	 * @param userId the user ID of this translation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this translation.
	 *
	 * @return the user uuid of this translation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this translation.
	 *
	 * @param userUuid the user uuid of this translation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this translation.
	 *
	 * @return the user name of this translation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this translation.
	 *
	 * @param userName the user name of this translation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this translation.
	 *
	 * @return the create date of this translation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this translation.
	 *
	 * @param createDate the create date of this translation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this translation.
	 *
	 * @return the modified date of this translation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this translation.
	 *
	 * @param modifiedDate the modified date of this translation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the key of this translation.
	 *
	 * @return the key of this translation
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this translation.
	 *
	 * @param key the key of this translation
	 */
	public void setKey(String key);

	/**
	 * Returns the language of this translation.
	 *
	 * @return the language of this translation
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this translation.
	 *
	 * @param language the language of this translation
	 */
	public void setLanguage(String language);

	/**
	 * Returns the value of this translation.
	 *
	 * @return the value of this translation
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this translation.
	 *
	 * @param value the value of this translation
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.dbb.common.language.provider.db.model.Translation translation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.dbb.common.language.provider.db.model.Translation>
		toCacheModel();

	@Override
	public it.dbb.common.language.provider.db.model.Translation
		toEscapedModel();

	@Override
	public it.dbb.common.language.provider.db.model.Translation
		toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}