/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.dbb.common.language.loader.db.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Language service. Represents a row in the &quot;CLL_Language&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.dbb.common.language.loader.db.model.impl.LanguageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.dbb.common.language.loader.db.model.impl.LanguageImpl}.
 * </p>
 *
 * @author danielebb
 * @see Language
 * @see it.dbb.common.language.loader.db.model.impl.LanguageImpl
 * @see it.dbb.common.language.loader.db.model.impl.LanguageModelImpl
 * @generated
 */
@ProviderType
public interface LanguageModel extends BaseModel<Language>, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a language model instance should use the {@link Language} interface instead.
	 */

	/**
	 * Returns the primary key of this language.
	 *
	 * @return the primary key of this language
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this language.
	 *
	 * @param primaryKey the primary key of this language
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this language.
	 *
	 * @return the uuid of this language
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this language.
	 *
	 * @param uuid the uuid of this language
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the language ID of this language.
	 *
	 * @return the language ID of this language
	 */
	public long getLanguageId();

	/**
	 * Sets the language ID of this language.
	 *
	 * @param languageId the language ID of this language
	 */
	public void setLanguageId(long languageId);

	/**
	 * Returns the company ID of this language.
	 *
	 * @return the company ID of this language
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this language.
	 *
	 * @param companyId the company ID of this language
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this language.
	 *
	 * @return the user ID of this language
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this language.
	 *
	 * @param userId the user ID of this language
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this language.
	 *
	 * @return the user uuid of this language
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this language.
	 *
	 * @param userUuid the user uuid of this language
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this language.
	 *
	 * @return the user name of this language
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this language.
	 *
	 * @param userName the user name of this language
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this language.
	 *
	 * @return the create date of this language
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this language.
	 *
	 * @param createDate the create date of this language
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this language.
	 *
	 * @return the modified date of this language
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this language.
	 *
	 * @param modifiedDate the modified date of this language
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the key of this language.
	 *
	 * @return the key of this language
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this language.
	 *
	 * @param key the key of this language
	 */
	public void setKey(String key);

	/**
	 * Returns the language code of this language.
	 *
	 * @return the language code of this language
	 */
	@AutoEscape
	public String getLanguageCode();

	/**
	 * Sets the language code of this language.
	 *
	 * @param languageCode the language code of this language
	 */
	public void setLanguageCode(String languageCode);

	/**
	 * Returns the value of this language.
	 *
	 * @return the value of this language
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this language.
	 *
	 * @param value the value of this language
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.dbb.common.language.loader.db.model.Language language);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.dbb.common.language.loader.db.model.Language> toCacheModel();

	@Override
	public it.dbb.common.language.loader.db.model.Language toEscapedModel();

	@Override
	public it.dbb.common.language.loader.db.model.Language toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}